packages:
  - packages/*
  - docs

catalog:
  '@types/node': ^22.17.0
  es-toolkit: ^1.39.8
  tailwindcss: 4.1.11
  tsdown: ^0.13.0
  vue: ^3.5.18

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@tailwindcss/oxide'
  - better-sqlite3
  - esbuild

publicHoistPattern:
  - rolldown-plugin-dts
